sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: aevMmL8U9EXmgZppBBZJah5d7I+8pUgvIW1CghJO2jCaiD3nPsafVHl6AE3ziAM64DmZvTez64xEtOQSItdgB2pklAsRcCqL1QX3IV4x2/5ccrwp/YPwHdHO5LflMcrAqTVnTQctbjkJ1prVLJA4so9MyVpmeZgGtySdJ+nT66T1EtyAb53ASFID5FDW/YSmyMTxHy2t1u6Pp2DxgGWKqZBU5ogGmE5WBoMoC256vg11ayMybLLIzlDfprOLkOtjgCoYlcgT2R8GLMpv6uB5Np7QxFEm58POliqs7iVmNidfwNB3d+n6lLEPAzmqyqBUdQjh/z92e/AFLvCGwZv04NtijkPfSfNFReoraGWB1ELL0pQgu0scmo691xr9JXHK9ME2n4l5D55uBtAwiGyE70kHDp5r9Gjt9lciQsgtx8vHWKyAf1mNkezDlzpPUYjZupfA8ucXIiNZDACdT5xXrU+JWP1eji7sDiTbmhtrHp/xI0iF43Bjv1eu4/R1DDcX3KRposKxMIGf2gDrYE9a5+iKs4RECjSQANF+ADzboAW6Kth7GuZAgf9kVcShCQ1L647IM5Tuo4f48SR2jM+JdUdfFzDrq4K0gQJy+VOmYSC1Rfpd3og7EZU5aVYgczwZOOCSYc+7cN1U9YzKTs0uc97VgSacptvXYy7YyotVlA4=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/The-Crown-of-Life_4541
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy